Traceback (most recent call last):
  File "/code/channel_service/orders/orders_updater.py", line 45, in <module>
    if __name__ == "__main__":
  File "/code/channel_service/orders/orders_updater.py", line 28, in update_orders_data
    order_cost_usd = order[2]
ValueError: invalid literal for int() with base 10: ''
[(1,), (2,), (21,), (22,), (23,), (24,), (25,), (26,), (27,), (28,), (29,), (30,), (31,), (32,), (33,), (34,), (35,), (36,), (37,), (38,), (39,), (40,), (41,), (42,), (43,), (44,), (45,), (3,), (46,), (47,), (48,), (49,), (50,), (4,), (5,), (6,), (7,), (8,), (9,), (10,), (11,), (12,), (13,), (14,), (15,), (16,), (17,), (18,), (19,), (20,)]
